# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Fischi_Engine_config = debug
  Fischi_Editor_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  Fischi_Engine_config = release
  Fischi_Editor_config = release
  Sandbox_config = release

else ifeq ($(config),dist)
  Fischi_Engine_config = dist
  Fischi_Editor_config = dist
  Sandbox_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Fischi-Engine Fischi-Editor Sandbox

.PHONY: all clean help $(PROJECTS) Editor Engine Test

all: $(PROJECTS)

Editor: Fischi-Editor

Engine: Fischi-Engine

Test: Sandbox

Fischi-Engine:
ifneq (,$(Fischi_Engine_config))
	@echo "==== Building Fischi-Engine ($(Fischi_Engine_config)) ===="
	@${MAKE} --no-print-directory -C src/Fischi-Engine -f Makefile config=$(Fischi_Engine_config)
endif

Fischi-Editor: Fischi-Engine
ifneq (,$(Fischi_Editor_config))
	@echo "==== Building Fischi-Editor ($(Fischi_Editor_config)) ===="
	@${MAKE} --no-print-directory -C src/Fischi-Editor -f Makefile config=$(Fischi_Editor_config)
endif

Sandbox: Fischi-Engine
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C src/Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C src/Fischi-Engine -f Makefile clean
	@${MAKE} --no-print-directory -C src/Fischi-Editor -f Makefile clean
	@${MAKE} --no-print-directory -C src/Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Fischi-Engine"
	@echo "   Fischi-Editor"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"